version: '3.8'

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: jupyter lab --ip=0.0.0.0 --port=8888 --allow-root
    environment:
          - JUPYTER_TOKEN=easy
#          - PASSWORD=password
    restart: unless-stopped
